webtalk_init -webtalk_dir D:/FPGA/FPGA_Binary_to_BCD/Binary_to_BCD/Binary_to_BCD.sim/sim_1/behav/xsim/xsim.dir/bin2BCD_4dig_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Dec  8 17:29:36 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6d403c49-e8cb-427e-a2bb-81fb33a4adef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9ff1b35cda804173b0b9d43e568b8d4d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 2700X Eight-Core Processor         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5996_KB" -context "xsim\\usage"
webtalk_transmit -clientid 52320329 -regid "" -xml D:/FPGA/FPGA_Binary_to_BCD/Binary_to_BCD/Binary_to_BCD.sim/sim_1/behav/xsim/xsim.dir/bin2BCD_4dig_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/FPGA/FPGA_Binary_to_BCD/Binary_to_BCD/Binary_to_BCD.sim/sim_1/behav/xsim/xsim.dir/bin2BCD_4dig_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/FPGA/FPGA_Binary_to_BCD/Binary_to_BCD/Binary_to_BCD.sim/sim_1/behav/xsim/xsim.dir/bin2BCD_4dig_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
